apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::827161319286:role/UdacityFlaskDeployCBKubectlRole0
      username: build 
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::827161319286:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1RA46G0ZCN7VC
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-05-21T13:23:26Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1594"
  uid: fa24560d-b98e-427d-9a92-3737e0f38de6